- src/001/Problem001.re
**Description:**
Add solution to problem 001 written in ReasonML.
> Feat: Add solution for problem 001 in ReasonML

- src/028/problem028.exs
> Minor formatting

- README.md
- src/001/001.cpp
* Solution of problem 001 in C++
* Att on Readme to contains C++ language
At first moment, I like to show the 'brute force' solution and proceed to my approach.
```cpp
#include <stdio.h>
#define LIMIT 1000
int main() {
unsigned result = 0;
for (unsigned i = 1; i < LIMIT; i++) {
if (!(i % 3) || !(i % 5)) {
result += i;
}
}
printf("Result is %u\n", result);
return 0;
}
```
So, this is the most common approach and the most common here I saw. And it's from it that I took my approach.
I observed that I can jump each 3 numbers and sum all 3-multiple numbers. This step was done by some of the users here and I done it too. This reduces the complexity to one-third and that is a great performance enhancement!
**Note:** On this moment I need to start my count with 3.
```cpp
for (unsigned i = 3; i < …
```
> Solution of 001 in C++

- src/004/p004.exs
- src/007/p007.exs
> Adding 004 & 007 elixir solutions

- src/097/README.md
> Formatting README

- src/009/p009.exs
Pretty straight-forward.
Using triple generators, filters out all the combinations but the one that complies with the conditions.
[Try it online!](https://tio.run/##VY9BDoIwEEX3nOIbN4JS6lIj7k1M9AotHbQJtqQF1MS7Y6kLdZbvzfz8oUY/tBvH@azovSukNgWZARRxoqi@WdU3hLOzsqEb5xsomwDBtGif3VVcrCNhFibF/UoGBnvwzw5QWweBXY41Y2YV0TRyQmL5DyuUWHPOkQcf9NeITGAJmUmUJaqs@hplt8HKrAqEjEo@xeBtM9Aq2t@KU3qK1x5H7TtWa@e7RZrEu8OJtX3nf95kMWQc3w)
```
Real time: 0.466 s
User time: 0.396 s
Sys. time: 0.113 s
CPU share: 109.20 %
Exit code: 0
```
> Adding 009 elixir solution

- src/002/p002.cpp
All the code discussed and presented here can be seen in my [personal repository](https://github.com/caian-gums/project-euler/).
Using some analysis about the problem and looking in the web for some better solutions as alternatives to 'brute force', I found something to explore a better approach to Fibonacci numbers: The  _Binet's Formula for the nth Fibonacci Number_. Let's deep dive.
First things first. Before trying to solve the problem, I wrote a fibonacci function as it is well known.
```cpp
#include <stdio.h>
#include <stdlib.h>
typedef unsigned long long ULL;
ULL fib(ULL i) {
if (i == 0) {
return 0;
}
if (i < 3) {
return 1;
}
return fib(i-1) + fib(i-2);
}
int main(int argc, char** argv) {
ULL i = strtoull(argv[1], NULL, 10);
ULL result = fib(i);
printf("The result is %llu\n", …
```
> Adding 002 solution in C++

- src/035/README.md
- src/035/p035.exs
Generates a stream of numbers from `1` to `1_000_000`, filtering out only the primes.
With that subset, generate the number rotations and filter for circular primes only. Then count the remaining objects.
Circular number generation is done only after prime filtering for performance reasons.
[Try it online!](https://tio.run/##dVPBbsIwDL3zFUaTUCJKaJl2QRo77cBpk3ZEqAqtC5HSlCUp64F/Z0mhUFo4NG387Gf72UUpKqFPp5fhtDR6uhFqiuoAWJsHKWZ5kZYS4VsXG4l5@PoGaTEAcMgehIn3WuRIIho48xwyLg320NkFtbrsgxWFvx0qqGABszM3wKcqc8al/CBkxpguSpWSec7tjplfbV0MdZSZIorCZAEac1IF4C7DdwgBVUodi3sNmmy6sNxiLIWxZLVDnsIRLBdyHUBTur/CeAw1vH4U6A@f5ezfRvpenlVNItqtwPW1Qe2rrQ2iUIY2TVf1eVzAUlncomap2AprCG3svZR1eDfKaXWLa4uwRRtfw0gcQBgAT5JLP@7rsaNXtu3YRydRAKteg24cRx@2pk94n/HVw0/czC3pKFH5sa/WN1XdFiVCJ6Xk@rZOXTnvE1z1uu3Y6LqMo4jeqwamkAdsKCPGojgMQ/80N …
> Adding problem 035

- src/024/README.md
- src/024/p024.exs
There are `n!` possible permutations of `n` objects.
If you choose the first one, there are `(n-1)!` possible permutations of the remaining objects.
If we divide (and floor) the intended index by `(n-1)!`, we get the corresponding index of the first digit and the remainder of this division gives us the new index for the sublist (now with an element removed).
This way we can compute individual indexes without the need of recursion, making this solution extremely fast!
[Try it online!](https://tio.run/##fZJNa8MwDIbv@RUau8TDTZOu@4T1tkPZYLuXENxYbQ2OExwnC6z77Zmdj7ajZYeA80p65FcyStEI3bbXV9Oq1NO1UFNUNWAnexw3Wc4rifCp87XELJzNgecegI0UsGGpybVg0o8ItfozROehhsDXDhWIMhHK4Ba1k5ji0MACor6uuTkpmETEGzkF6qwyzKC/2iHjMYWEAkvToV8nwt4pMewX8KqqLNBYoy7RJ05Z9j2DSnGxFab0yTlaitJQEIpj08N7jwDfICgYJiT8wEunALjk4Wjx7/YvKPIiY …
> Adding problem 024

- src/010/problem010.exs
Generates primes until limiting condition is met, then sum all occurrences.
A bit slow, could be improved if generator checks increased by 2 instead of 1 after checking if 3 is prime (since 2 is the only even prime).
[Try it online!](https://tio.run/##ZZDPToQwEIfvPMVsTMg0YikcN4onD5408QEIG2alsS3YP7scfHesJbjGPTRN5zfzfc2QkrO0y3KzK4Oz5UGakswJKJWzno567IMieLXjQZEWlYB@zABiMoF07WSlJqxZEct78DbQVTgzOA9kYIYG6nUa4MkEzTulHhFrzu0YTI973fmBu0/r4wyLyKNBw@CuAUsa5wLiY/cAAsj0LFLilW22dzJkO0@r0yHbRG/eUqe59CnGuoAc8@q2YizFX83WcZQq9mD@@@987blYwI3qRBv4yviP57sPas@DVJEUWXAPdSuE@DkXd1qDCxo3U7I9v/ApePdn6Typs2X5Bg)
```
Real time: 24.165 s
User time: 23.646 s
Sys. time: 0.341 s
CPU share: 99.27 %
Exit code: 0
```
> Adding 010 elixir solution

- src/028/p028.cpp
For an n by n grid, and n being odd, the number in the top right corner is n^2. 
The other corners are given by: n^2-n+1, n^2-2n+2, and n^2-3n+3. 
Adding these together gives the quadratic, `4n^2 - 6n + 6`. 
Then all I had to do was create a loop from 3 to 1003 in steps of 2.
[Try it online!](https://tio.run/##VU7LCoMwELznKxZ60RZBa@lF7V1ob/0BSdYSiInk0Uvx29ON1kMXdneYZWYH@TwX1DEepOYqCIRWGuctDtONBSf1C/QwoZsHjuC8aBg7CBylRrj3j/4JVVnWjEntwRn1xiyHDwOqlQkTdFA1KzEaC1liJXF1Q6vdLBI8dXDelamSkrgLHOmYuoDsSiBLqMrzzXJZp0UfrE6Shi1blGmQ@i@JRReUp8e/kJuem@ChbfcrIdRCJZcYvw)
```
Real time: 0.334 s
User time: 0.250 s
Sys. time: 0.075 s
CPU share: 97.41 %
Exit code: 0
```
> Feat: Adds C++ 028

- README.md
- src/001/p001.scala
Basically, as all the solutions for other languages, checks if a given number `x mod 3` or `mod 5` is equals to zero, reducing to the sum of elements.
Using the [tio](https://tio.run/#), I got the following results:
```
Real time: 3.294 s
User time: 5.224 s
Sys. time: 0.343 s
CPU share: 169.01 %
Exit code: 0
```
> Feat: Adds Scala 001

- src/009/p009.lua
Two loops and an if statement.
A third loop is not required since we can infer C's value with `a + b + c = 1000`.
[Try it online!](https://tio.run/##Tc9BDoMgEAXQPaf4TTeKNuqiSw4zIqYmdDAIXt9i0dYFkDxmfmZspG2735q4@KafuDG8wkYSY2QdJsdYnF1NUQrAOk0Ws3dD1AEKXbLReZBqazzbFoNLkq1XVHX1BQG9t7RJHujToYOX@E4fhCppBX3oNILkF2UPpaClBvGQq4@c8DJ8lOMyFkGmKPmLMjyI/5tvb0L0fDaJHUVez5sl2j3m3Hv2E4cicym27QM)
```
Real time: 0.026 s
User time: 0.021 s
Sys. time: 0.004 s
CPU share: 98.93 %
Exit code: 0
```
> Feat: Adds Lua 009

- README.md
- src/028/p028.java
For an n by n grid, and n being odd, the number in the top right corner is n^2.
The other corners are given by: n^2-n+1, n^2-2n+2, and n^2-3n+3.
Adding these together gives the quadratic, `4n^2 - 6n + 6`.
Then all I had to do was create a loop from 3 to 1003 in steps of 2.
[Try it online!](https://tio.run/##XVDLDoIwELzzFXssGA2oMSbqV3g0HipUslgKabckxvDtuBV8xL10MrM7O9tKdnJeFbdhaP1FYw65ls5Bmy638IiAq7XYSVLgSBLraAhcozsl4qkh1Iv1NRwg233Ia2NBBAWZX@342UOWpi80O8Dy1yBUMGB@nWCCMAexgYTnGWVx/HXtP8gq8taEsVHtozHweMiUt2uwgFqiEUeyaMrTGaQt3X94q5zXxDmn2777jndHql40nhb8FYa0EWNz/N7aR8PwBA).
```
Real time: 1.016 s
User time: 1.338 s
Sys. time: 0.167 s
CPU share: 148.11 %
```
> Feat: Adds Java 028

- src/002/p002.scala
Using the Binet's Fibonacci technique to calculate the `fib(n)`. Iteratively calculates the `fib(n)` until reach the limit(`4e6`), summing at each calculation.
[Try it online!](https://tio.run/##ZVGxTsMwFNzzFbcg7JYmtAKGig4wVGKABXVCCDlp0hjFdrCdRgj124PjmqSoi6279@7eO9tkrGJdx0WttIXpUSyYLeNatdE5a760jSKVfuaZxTPjEj8RsM0LFDwlcoknaak/sfIlIJn4CxNsDJc7PHKZ20uDNU@VZFnG8dKINNd/XaW19TJJ@nGt0tU2blVVaCbiTInEi80gPSrXSovGbVhaUQWXxN@EuBSEzDFFvzi5pfQKkmKGwM/@8RQJvGLhuyZDkcZWuUjO8xCFuMJlJ0zvzBIPWrPvt1erXbp3F34j@Zh@zzSkQ9cDcg/1sWdVk5@xphGe82Rb8ioHGbvvcZPf0WAL8OK0eIEFVk5LB6PpapwUJLIn5wGcruH/jvrC4Ti9dmFsJUlwoz76oet@AQ "Scala – Try It Online")
```
Real time: 2.517 s
User time: 3.627 s
Sys. time: 0.348 s
CPU share: 157.94 %
Exit code: 0
```
> Feat: Adds Scala 002

- README.md
- src/001/p001.hs
- src/002/p002.hs
- src/003/p003.hs
- src/004/p004.hs
- src/005/p005.hs
- src/006/p006.hs
Pretty regular filter-and-sum functional solution.
I chose to keep it a bit more generic by creating a function (`divisibleByAny`) that tests if a number is divisible by any number in a list, so if you wanted to sum the multiples of 3, 5 and 7 instead, you can just swap `[3, 5]` to `[3, 5, 7]`.
Pretty simple solution.
It starts by creating an infinite list of Fibonacci numbers, then taking all elements that do not exceed 4 million, then filtering out the odd numbers and returning the sum.
This one is a bit more interesting.
It uses the following algorithm to find all prime factors of `n`:
- search for the first divisor `d` in `[2 .. sqrt n]`.
- if `d` does not exist, `n` is prime.
- if `d` exists, return `[d] + prime_factors(n / d)`
It is quite faster than calculating all factors then …
> Add Haskell 00{1..6}

- src/004/p004.scala
Simply makes the multiplication of every pair of three digits (`100 to 999`), find the palindromes and get the maximum of them, using some functional programming ideas.
[Benchmark](https://tio.run/##dY/LasMwFET3/opZSoWadGlTF5pdFl2VrkIIqn0dFPQI10qwCf52V35gKCHa3ZnDaKYplVHD4H/PVAZ8Ke1wT4CKaujmeFFGu4q9JeGuNsfOBZlj670h5VBMKBCtNPjvwNqdUBT/7pTpRtxQBPtkCbbxF6H41OT4ZFbdfkYPMfrH6bDm3pSJbKvt1UZNTBpQe1788bV4f4V422wQPLIsk6vTPXF6dJpMJVq8oJtFmdbaBGIxrpQoPh63S5nGKsmEX2LbYJxYuslpW58Mwx8 "Scala – Try It Online")
```
Real time: 3.928 s
User time: 6.255 s
Sys. time: 0.394 s
CPU share: 169.29 %
Exit code: 0
```
> Feat: Adds Scala 004

- src/012/p012.exs
```elixir
numbers() # Enumerates integers
|> Stream.take_while(&(condition(&1))) # Iterates until condition is met
|> Enum.max # Takes last number from stream
|> Kernel.+(1)
|> triangle_number
```
```
Real time: 5.185 s
User time: 4.958 s
Sys. time: 0.205 s
CPU share: 99.56 %
```
> Feat: Adds Elixir 012

- src/003/p003.scala
To verify if a given number is prime, simply check from `2..sqrt(n)` for odd numbers, as there is no need to check more than that.
Finds the prime numbers that compose the given number an take the last of inserted on the set.
*Note: When calling `.last` on a set in scala, it takes the last inserted element*
[Benchmark](https://tio.run/##dVFLTwIxGLzvr5iLSRvjysNXiGuiNxM8EU@EkIIt1HRbbL/VEOG3r92yLFw89DGd6ffNtGEpjKhrXW6cJ4QG5aWgdR6@PGWZW3zKJeFNaIvfDPiQCjrMN16XktkRXi3xEV6cM1JYFEkDaAUWUYEBdjuk3ZDDS6q8BflKnqkuoijyvY5XwgSZJYVyHkzj8QpDVJa0QeOKWZ6Ti52x2GLAk/JUTf9brW28z9ocZQzFhF@FEZ69F9vphLy2q1kM9G41dWm@hW8y4K7Xe7jt39zHMRx3jIrMoEMhoomkaXQ3Y/zQ92etjWzMPaHP25onv6r1ezxH6hWpa6gm59jZVUcFXBZQLdxDxmxnF1XD9o9sdpjTEv/LkrEs5EYE4ukV9nX9Bw "Scala – Try It Online")
```
Real time: 3.335 s
User time: 5.225 s
Sys. …
```
> Feat: Adds Scala 003

- README.md
- src/001/p001.clj
Same as always. Iterate from 0 to 1000, filtering multiples of 3 or 5 and then sum them.
[Try it online!](https://tio.run/##dc7BCoMwEATQu18xIMIuIkRKj/oj4kF0LS0xkdX4@7H2IkKd8zxmeus/QSVGGmR0WLzdBE0LKuoapJ17CUpjDCf4ExrfdhVFSl5B1RfIhKzEg3EjrvwUz0PwzYrKEHpBfhQSmtWBfkeZY9wB)
```
Real time: 2.820 s
User time: 4.846 s
Sys. time: 0.170 s
CPU share: 177.89 %
Exit code: 0
```
> Adding 001 (first) clojure solution!

- src/004/p004.go
- src/004/p004.lua
Straightforward solution, just loops over two ranges and tries to find the largest product palindrome.
[Go](https://tio.run/##ZZFLb4MwEITP9q/Ycohwo6Skx7bpvbfcoxxcYpCpH8gPLhG/nXqJoWorIVm78401Y1o7TT2vv3grQHNpKJW6ty5ASUnR6FCkwwdXWzMUlFHaRFOD9CeupLk6q0UpTR8DSBMYfFqr4EZJMsDLEbJv/xEsv2OMksY6kKhWr@l8AyVMmUD29Jzm7RbtRDboPcsLPMy3nBdoJ3eHy4wQJ0J0BhquvEjzSPHLy@CioGMO660aRMkwIToH7kBx1wo/h/4f6FBV1U8UVLusdqvaZZX0zl5jHRCQ8Agd7lL6Xw@UGQabDSz8@5phvoYs03EhcDv@7ZWptRr@sNTshoCPao6R66ZeOuxPLlVUprzLLBmn6Rs)
```
Real time: 0.254 s
User time: 0.205 s
Sys. time: 0.077 s
CPU share: 111.04 %
```
[Lua](https://tio.run/##XZDBDoMgEETvfMU2vWjTVK8e7K80KGtLQhezgL9PMaA2XtgwjxkYTJAxXi9NcNwMmhqkBUyQYgo0em0JtHvN0mhSbL9YUS0AjB2lAecZevA2TU3vTBh9YMqoh0wejAuywypta4GkxBHurFmwOjKN5Dc6n3LbpE2WQfbtHbquA2WTkrXhpG3uma0K4@qWcIOhMD3t4Llf …
> Feat: Adds Go and Lua 004

- src/028/p028.clj
[Problem 028 on wiki](/FrankKair/polyglot-euler/wiki/Problem-028)
[Try it online!](https://tio.run/##ZY7BCsMgEETvfsUc3ZaChtJDoV8SQgjRlhSrQUnw761KSSDdy@zsPHZ3NO69eJ0SV/ppEebJD6ZX0/Dqw/JBGzsG8NFZlTV3D0RIgtxdk52o9q5N0OBn8BOuOYlUx1vxS0luRcsSOsbH45VrqBRjv/@cWTXa7h@WQsjKzd7mtHBEKX0B)
```
Real time: 3.211 s
User time: 4.961 s
Sys. time: 0.443 s
CPU share: 168.31 %
Exit code: 0
```
> Adding 028 clojure solution

- src/009/README.md
- src/009/p009.hs
- src/010/p010.hs
- src/012/p012.hs
[009 - Try it online!](https://tio.run/##fZBLS8QwFIX3@RVn4aLVtnQG3Ax2FiKCIrhQcFE6cPtwGkzTktwuBvzvNZ0OPiBjSELu5RzOl9uS/WiUmibZDb1h3BFT8iQtI3iXug6FGA7c0r43DelXIwfVMDYbPGhu9oYUNLItAh1h3iHiLW77XvlcAUUoI1QhMgG3aLfGFUp3Zxmq3VqIblTstId7aSyfDcu/04o5TvttFela1sSNPcXNzcfR/uHA/Ed4WH/cR6/UIFyidKcSgheRfZPcvozdKk3Tfym9hgUqP8EcW7ELiVGG@HSPmxj5Kkmu07Rwit9l4QZFjmiOfEYQLlWGwUjNuIB3HB4EMU1f "Haskell – Try It Online")
[010 - Try it online!](https://tio.run/##ZU@7DoJAEOzvK6awAKPGYGfAws5KCxMLJfHUVYgHd7mDiIn/jseBr7jV7M7OzG7CzZWEqGul04wMplNsF3lBF9Ix62YRAthxhQcqhENsJ6NRPEBqHI8qZm9od7kQ8HYKw5lt95k87aEww9iHd@bHQmqzlmt9R@Uz2LolpMmhpn43rFvBr7RJUkEvT9VXCCOrRnsdY6bMlueVa@Yk5K35oXuhEXTwf@0gy/yEyGVbEr3vsLClPykZT3PnvITnt13UkHlhhX/ewdgVq@sn "Haskell – Try It Online")
[012 - Try it …
> Feat: Adds Haskell 009 010 012

- src/002/p002.swift
- src/010/p010.swift
Optimizes Swift 010 using [Sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes).
[Swift](https://tio.run/##dVLbSsNAEH3PV4wgsrF1SatPxSgIPvggfkApkjYTu2GzKXtJhbbfHie726BQ9yE7OXPOXE5i9qKyD31fObUBI7DDj@pVF7Y1dosKDfuEdetUuYA3ZVO4e4IlBSs4JECnKzTstGjQQA4s45x7csqbYgcHuM4gz2EOx@MQ3sAMrnLI4JSMYuUaUt779/1WSPTIrX8@5qF17HWW1CQYScmYCur6kmo4YcplvSJ1VUiDf7I1THzRETyN0dCKkvMkwP7SaJ1WsSZHoiBZhiVLeSUL@@6XZ0KV@O19m9Lg0uECXtpWehMJfAahxi6iAk8f/JqROHZQQv4a5csVugylBp7VdCOt8h8/gr5wHJ8WCF@6lR2y8yjRq8i/9BfMM39SrrF0G2TZFCbpUE2iJZ1x0pKxsWpCxijLApwmff8D)
```
Real time: 2.604 s
User time: 2.482 s
Sys. time: 0.085 s
CPU share: 98.58 %
```
> Optimizes Swift 010

- src/015/p015.cpp
Basically all these languages call a `combination` function to output the desired number of routes.
Note: [Combination](https://en.wikipedia.org/wiki/Combination) is also known as `n choose k`.
[C++](https://tio.run/##VU7LbsMgELzzFSP14tSJ4la9YfdfCN5WKHixePRS5dvdDQ5SuhLMMjs7DNl1PcnZthfH1peZMLqQciSzfKqSHH@DzUJpNZaQ8qyV8kFIG5aLY5Nd4K4SfETF6wG/ClK7DBPedH1/hYhd6oQctMCIq0Dft5V7WbxOYJzg9BN3nkTeN6tbvSPlEhlWq9sjVAr@h7rm1uZPST@GI96HQ91wnLEYx92/wJFS8VkCPrz2D20oGePYptIRz/5us21/)
```
Real time: 0.395 s
User time: 0.328 s
Sys. time: 0.058 s
CPU share: 97.80 %
```
> Feat: C++ 015

- src/002/p002.lua
- src/005/p005.lua
[Lua 002](https://tio.run/##ZY/dCoMwDIXv@xQZY2CZoJNdzmeRViMWYjtqq4/v@iOysV60fCfJ6Ql5se/XS@UXW0mlK9QrkBds9Lp3ymhY/NzhiroblVw6iWS2gtSsHGcAZHpBsQVaqE8WgR4nyUANC7hNijDgC9I8DCaIAGoM2g0aaIMHuAl1kuGwjfcdZNJQD@kVZXKVZfgq13LFovM2RWZR@FrC0IoF/2n52@pZp8PzbA5vcfHkYozD4W2VdkWWOdv3Dw)
```
Real time: 0.006 s
User time: 0.001 s
Sys. time: 0.005 s
CPU share: 98.30 %
```
[Lua 005](https://tio.run/##bZBdbsMgEITffYqpqkpO5cRO3tNL9AARGJystECEwVVO70L8kzbtC9odZplv4SjG8fWljr2vJdla2wEcRdFF2wZyFudWlaKC3BTA14VYQ@IDDZRLAsCuFQzjFI4QeIO8qyJ1UyVTlW5TrW0@vQ7RW4git48Ubs2asljwnqbrHwC/R3ojmHUfTooGUlqd5K1kMhTyGxOW133kkAj2SeqcBx0PFe6mhX@1ZIKpqUCbZ14jwmXXsXN@Nv2hcTzoMs9tt/ic0WCjkdojE/Yk89/d4IU9a@wRHA7N7hHx3z6HZs552mdJu3qyYSUax28)
```
Real time: 0.007 s
User time: 0.002 s
Sys. time: 0.004 s
CPU share: 81.28 %
```
> Feat: Lua 002 005

- README.md
- src/001/p001.d
- src/002/p002.d
- src/015/p015.d
- src/028/p028.d
**001**
Simple loop filtering % 3 == 0 and % 5 == 0.
**002**
Simple iterative Fibonacci sequence.
**015**
Basically calls a `combination` function to output the desired number of routes.
Note: [Combination](https://en.wikipedia.org/wiki/Combination) is also known as `n choose k`.
**028**
[Problem 028 Wiki](/FrankKair/polyglot-euler/wiki/Problem-028)
[001](https://tio.run/##VU7LCsMgELzvV8ylYAgUQ@nJ5mMKMbCQaDEmPTT5druaPhdWd2ZndLqUeLz5EDHF7ijN3hCxE@yHxaoKD4JUYeYRLbQpRO8DVGZZuMbIdUGjtZaprt@u4uxFhwNOaMWMdUVG54J@dbnyD3ULNh92o@8ZbJyDyyJDG9HiucN4ZfcXMthpHqJkeuXfn7oHjnZwat9W2Z/SEw)
```
Real time: 0.485 s
User time: 0.266 s
Sys. time: 0.092 s
CPU share: 73.99 %
```
[002](https://tio.run/##ZVDLCoNADLz7FbkUtgilld62fou4mNLAPmRd9VD67TbRVi0N7GFmMpNsmmki14aYoEvNiR8FnWXkGfeuwgF9dSfTVQZtGJXwlhylIzwz4BKihhIu …
> D 001 002 015 028

- CONTRIBUTING.md
This pull request tries to come up with a framework and guideline for contributions, as discussed in #14.
What do you guys think?
> Feat: Adds CONTRIBUTING.md

- .github/pull_request_template.md
- README.md
Adds `CONTRIBUTING.md` to `README.md` file and modifies PR template to include a checkbox.
I think this solves #14.
What do you people think?
> CONTRIBUTING.md -> README.md

- src/036/p036.cr
- src/036/p036.go
- src/036/p036.lua
- src/036/p036.swift
Simple iteration filtering double base palindromes.
```crystal
(1..limit).select { |x| x.double_base_palindrome }.sum
```
`Crystal` and `Swift` use patten matching (case/when, switch/case respectively) to decide which base palindrome to call.
`Go` and `Lua` use a an if statement.
`Crystal` and `Swift` compose a range with select/filter and sum/reduce.
`Go` and `Lua` use a for loop with an if statement.
[Crystal](https://tio.run/##hVDJasMwEL37K@YUrIuQfQyEQm499wOEl0lrGEtBI2Wh6bc7km0ak4UcRsz2llHjzuwrGoaGKmb48q4z3xlAizvYV9SZ1tkeP2ANW2spDgAYaQebDTg8oGOMPTRtliJj70Lj4dP4mcKEvkanb0x5XTGKkaeJGaRyrI4/aKAc00lCeqs5L4Vc2LhtFup@9WEvOZre2UxrQ02ok@TC0f9N8tFsoQSsVq@mpVjenhQ49Pq5CusayR5z6vrOJ1xeSDkVMtJj/LVfuJwucJLPCeBPRvaFlKVD8v5estBKqRRiQu@D5xk@DFc)
```
Real time: 1.942 s
User time: 2.288 s
Sys. time: …
```
> Crystal Go Lua Swift 036

- src/018/p018.exs
- src/022/p022.exs
I'm removing the problem description from Elixir's source code, since it's not really needed.
Also giving you guys a chance to catch up with with my verbosity 🙃
> Removing redundant information

- src/097/p097.go
- src/097/p097.java
Uses modules `math/big` and `BigInteger` (`Go` and `Java` respectively) to perform multiplications and exponentiations.
We use a "%" / remainder to keep track only of the last digits of the big number.
Go
```
Real time: 0.693 s
User time: 0.209 s
Sys. time: 0.283 s
CPU share: 70.99 %
```
Java
```
Real time: 0.649 s
User time: 0.868 s
Sys. time: 0.084 s
CPU share: 146.66 %
```
> Go Java 097

- src/001/p001.js
Enhanced the solution of problem 001 (JS) to a functional approach
*Try it online* results: 
```
Real time: 0.099 s
User time: 0.086 s
Sys. time: 0.013 s
CPU share: 99.50 %
Exit code: 0
```
[link to the test](https://tio.run/##RY/NCsIwEITveYq9CFvUUhEPpUTwUUK7lUialPwUxfrsMTZVbzPfzC67NzEJ11o5@r02HcXYB916aTQ4oybCAp4MwJIPVsPFWvHAuq6LxADKXiqF1WoGMSJOQgXagdQd3Qvg56xgC4f/iCebe588iw0cgXMOFczzD50yWgctdaElRBeGXa4s@5NN27Nv2Iux1mjn08EuKA/8@0WzcKOoVOaKOU0wxjc "JavaScript (Node.js) – Try It Online")
> Enhances solution to a functional approach

- src/025/025.py
- src/028/028.py
- src/036/036.py
- src/097/097.py
**025**
Simple Fibonacci iteration checking length of the number.
**028**
[Wiki](https://github.com/FrankKair/polyglot-euler/wiki/Problem-028)
**036**
Simple iteration filtering double base palindromes.
**097**
Uses modular exponentiation (`pow(2, 7830457, mod)`) and `% mod` to keep track of the last ten digits.
[025](https://tio.run/##PY7BDoMgDIbvPEWXHYRoos6bmc/SSMRIgtUAuu3pGQOznv5@bb90//hloy6E@60@nK2lplrRCXvmbFIzuM2cioueQSxNk3rDAF3qxpjalGRMD5bia9FGgVHEnbdcCgFPaJumyYJ0VqV9WUVBCfLPs7z8OROzyh@WMmaM6RkQaVwVIgwDFIjrqAmx6K9tdxgfvdfDCe5Wk@d5JFgIXw)
```
Real time: 0.078 s
User time: 0.063 s
Sys. time: 0.011 s
CPU share: 95.17 %
``` …
> Python 025 028 036 097

- src/021/p021.py
- src/021/p021.rs
- src/021/p021.swift
Straightforward solution, filters a range by `amicable` numbers.
[Python](https://tio.run/##fVDJbsMgEL3zFVNVVUCN4ri5VfK1P1FVCMekQTJLWSL3610wuEZRVQ4c3szbxnz7q1aneX58aIKzTS9Uw9UNTMaRkEZbD5L5K0Jo4Be4sLPX1mEVZM8teUUQXwGhg/f2Y0GCMdzSXgc1RFQoj5PGwX1Zv1IJPEOb6drCFJfAMvXJ8cu@pheL9MQFMhee4n7XwXGbVTEOLLLVgJNr2W9gIuS/3SlPLffBqnVYKjMpzqwf@Z@dqQsyNow/vjtNVtwyx7wVZ0tePN/Y6HgdYqPV4pVEdMgBnR5vHJdchZ040/1l2z20x/hIivVba1qEIkKpYpJTmjx3lEomFKW7VdaF0aem2WwBjU03ziOC5vkH)
```
Real time: 0.181 s
User time: 0.168 s
Sys. time: 0.011 s
CPU share: 98.76 %
```
[Rust](https://tio.run/##dVLLboMwELzzFZtIrWy1dUNyS0o@o5eqQkBtxZKxqR8REuHbqR2c4ErtHhDamdmdHdDO2GliEljVWKUNknvguy2GlyO …
> Python Rust Swift 021

- src/021/p021.cr
- src/021/p021.rb
Straightforward solution, filters a range by `amicable` numbers.
[Crystal](https://tio.run/##bY/BbsMgEETv@Yq5tILLNu45Vs899AuqyiIYK5aIcWCpXCn/7gJyE1SFC/A0Mzur/U9gZdc1sI@a8T7xDujNgEFpdj6kH/7eaPHZfBUS59n47uji1Cf6ofhE4eJZBGMHSey6scjEK1EllWSUPqF3uC7XIgDGAdmEJyxoW@w3fB96OEAs8iEuxhcs1UTATP2uvu@LZLJtp86jVkdr3mpJF@I5bZNTaUOUUJF4w9FPSWmDuXVOfStr0T3g/7Jyi9Ik9wjOfpsERUPU7NORlBKMZvFMt46yOItnjhw207r@Ag)
```
Real time: 1.543 s
User time: 1.755 s
Sys. time: 0.312 s
CPU share: 133.89 %
```
[Ruby](https://tio.run/##bZDNTsMwEITveYpBCCkRktNwRI165sATIBQ5zoZGSp3gn8qI8uzBNqH1Ib7Y@2l2dtbKtl/Lcn9XWq3KdpAlyTOUh5kYudZ4kYY@SGVARz16LsyktK/w/0aNt@o9EjvPpJp2srLz9JWbI9OfyuSaxr5 …
> Crystal Ruby 021

- CONTRIBUTING.md
- README.md
- src/001/p001.pl
- src/002/p002.pl
001: Iterates over range and filters out numbers.
002: Iterative Fibonacci summing even numbers.
[001](https://tio.run/##TY7BCoMwEETv@xVT2oLiQUvxlPozlggBjbJJhFL99jRZpO0ckp2XWTKL5rGN8Xyqg@O6N7bWdsWSKAWn4Tybp1dELvRw87hqvAlJ0wsXFyZ0aJSAYWYUmRph@X7g1jQyVlV57GWZAUV6vuKOLmWxbRDbiv1PZsk3VZci6st3@p2sfWArMUU7Ue7A2oXRpyJSWdHCxvriwKWiGD8)
```
Real time: 0.009 s
User time: 0.004 s
Sys. time: 0.005 s
CPU share: 98.23 %
```
[002](https://tio.run/##TY/NCsIwEITv@xQrKlg8tBY9xT5MKysG0hjyUxHps8dNWlvnsDAfs5OsIasuMW43ZXC27KQuSQ9omEJwhM5befMCwIUO3VMNhB9AVv/GXYsNnsRiO7b1al3oGVQTeD2kIjxw5ornKquYm5Jy@NikDnlPc481Nsv2r9JTbzClVszZtNf@kfStHJ3YmKclH6zODwkYAVKdJReU53Q@TICxUvvD …
> Perl 001 002

- CONTRIBUTING.md
- README.md
- src/001/p001.fut
- [?] I checked [CONTRIBUTING.md](https://github.com/FrankKair/polyglot-euler/blob/master/CONTRIBUTING.md) for my programming language of choice.
There is no section about Futhark on CONTRIBUTING.md.
first we define a `divisible` predicate, return true if our input is either divisible by 3 or 5
then our main is just a reduction summing over after filtering out only `divisible` values.
Futhark is not available on TIO, it does however compile to C, which I could test there via gcc.
[Try it online!](https://tio.run/##7V17cxs3kv/79ClgbUkiKZISJVmWLcspb2LvuipxcnH2dq98XtaIHEoTkzPMPPRwrM@@190AZgAMBoORHSd7dandRMQAP3Q3uhuN92x0MZv9619/iuLZspiH7GmWz6M4H18@29DS5uEC0zb2BhtswF7FUR4FyygL8iiJNwZ7GxtZnhaznC2K/DJI309nSZyHNzn@dxFdsNOW7wN7@jQOr3v9042r …
> Futhark 001

- src/001/p001.ts
Iterates over range and filters out numbers.
[Try it online](https://tio.run/##TY7BCsIwEETv@Yq5CAkBqYgXtT9jSWUhTUqyEcT222OSqnhY2Jk37Cw/ZxOHQDPnPCY3MHmH6O3DSHWGS9PNBLwEYA0jpunn9eiKO/oAWRH9gwsIVxy6rm5aq3YAoBGSsMMRfQlhWVDVqalvBrUEugc1uYptguEUXGViFWLwLnLxYrJc@j7vNttbs7f@Ljeocn4D)
```
Real time: 2.468 s
User time: 2.988 s
Sys. time: 0.205 s
CPU share: 129.36 %
```
> TypeScript 001

- CONTRIBUTING.md
- README.md
- src/001/p001.scm
Iterates over range and filters out numbers.
I couldn't use TIO to profile this programming language. 😕
> Feat: Adds Scheme 001

- src/041/README.md
- src/041/p041.py
- src/041/p041.rb
A number is divisible by 3 (and therefore not prime) if the sum of its digits is divisible by 3.
Since 1+2+...+8+9 = 45 (divisible by 3) and 1+2+...+7+8 = 36 (divisible by 3) but 1+2+...+6+7 = 28 (not divisible by 3), the largest pandigital prime is a 7 digit number. 
[Python](https://tio.run/##hVHLTsMwELz7KxYhFEdUlLY8JKRe@QLulqs6rVH8YL2uytcHO05oUCnsJcrM7uzO2H/S3tlV111fzWPA@UbbubIH8AVnDToDRtIetPEOCcIHUkE1KSTn2jBSXqGJJEk7GxhjW9WAR20Ut9FsFNYvDFLpBso/rNewKFguVBTRwqtsg@rB6JOg2Lhot7AGbYnn3aNYDbew6Psah3BMPKC0O8WXs@lkfVqQFh/zziJwwnNZdaRp43DhTZm4/9l8dukAvGFUg@9W4k4FEr1/4aXd6p0m2fLhnkt8MlpMTbMUrQ …
> Python Ruby 041

- CONTRIBUTING.md
- README.md
- src/001/p001.groovy
Iterates over range and filters out numbers.
[Try it online!](https://tio.run/##JczLCsMgFITh/XmK2QR0I4bQXV30XWKKcKLFSyAkPru1dfnPwPeOIRxna6vdkAIfFgYXAWJW6jlrraXanF9fzLjgMiYsMAYa9z3yMbKqVHYhqRL9qGhT4dytv9n3T3Q@sxfjkNTaFw)
```
Real time: 0.924 s
User time: 1.269 s
Sys. time: 0.161 s
CPU share: 154.75 %
```
> Groovy 001

- src/028/p028.groovy
https://github.com/FrankKair/polyglot-euler/wiki/Problem-028
[Try it online!](https://tio.run/##JY3BDoMgEETv@xVzhKoNaNObfk3RkFAxgCbG@O10oYdNZnZeZpbg/XHm/DEzoneHwYiLgOr3LzvNbnjGZDZopYYWfYsLFt3EASrUjHjhwb9yHcSbhShKS8nQTRWjm6jUBhN3l7i57glJW7Brcqv4B5Jy/gE)
```
Real time: 0.869 s
User time: 1.132 s
Sys. time: 0.168 s
CPU share: 149.60 %
```
> Groovy 028

- src/014/p014.hs
- src/014/p014.rs
Iterating through all numbers until one million, calculating their collatz number and storing the largest one.
```
real 2.67
user 2.67
sys 0.00
```
> Haskell 014 / Fix Rust 014

- src/015/p015.hs
- src/016/p016.hs
- src/018/README.md
- src/020/p020.hs
P015
```
real 0.00
user 0.00
sys 0.00
```
P016
```
real 0.00
user 0.00
sys 0.00
```
P020
```
real 0.00
user 0.00
sys 0.00
```
> Haskell 015, 016 & 020

- src/058/README.md
- src/058/p058.clj
The function `spiral-corners` receives as input the side length of the spiral and returns what numbers are on the corner of this spiral. The equations for all corners are `side*side - n*(side-1)` with `n` ranging from 0-4:
```clojure
(defn spiral-corners [side]
(cond
(= side 1) '(1)
:else (map #(- (* side side) (* % (dec side)))
(range 0 4))))
```
The function `prime-corners-count` goes one step further and counts the number of primes on corners given the side length:
```clojure
(defn prime-corners-count [side]
(->> (spiral-corners side)
(filter prime?)
(count)))
```
Having these functions, we can define the `solve` function. We start with a stream of numbers `1, 3, 5, 7...` which represent the side lengths of the spirals. We map …
> Clojure 058

- src/022/p022.coco
* `parse` does just that: reads the file, splits into names and sorts it
* `score` calculates the score of a single name, according to the rules
* `names` "indexes" the iterator, by zipping it to a `range`, then multiplies the tuple (index, score), and sums the whole thing
using `$ time coconut -n -r p022.coco`
```
real    0m2.162s
user    0m2.085s
sys     0m0.071s
```
> Coconut 022

- src/022/p022.clj
* `names` is a lazy list of the already split and sorted names
* `score` gets and index and a name, and multiplies the inc'ed index by be name's score, as the rule describes
* `solve` just iterates over the sorted list, calculating the score and summing it up.
using `time` cause can't feed the file to tio.run ):
```
real    0m2.818s
user    0m11.073s
sys     0m0.425s
```
> Clojure 022

- README.md
> Replacing Bash with Shell

- src/022/p022.lua
- ✅I checked [CONTRIBUTING.md](https://github.com/FrankKair/polyglot-euler/blob/master/CONTRIBUTING.md) for my programming language of choice.
```
lua p022.lua  0.02s user 0.00s system 91% cpu 0.027 total
```
> Adds Lua 022

- src/001/p001.rs
- src/006/p006.rs
P001: no need to create iterator, since `(1..1000)` already returns one, and no need to explicitly borrow/reference
P006: by having the whole state in a tuple, we can iterate only once
P001: [Try it online!](https://tio.run/##PY3BCgIhGITvPsW0ECiUWEunsHfp4ILgWujvsrD67CZuNbdhZr4JKVKtk0d8ucVwgfMDdrxiY2jiSsqLUkrIyToygec1Y8URI7SGQt7drTvRJ3/JmGYuWGGs0een9Q2@U50hBBOTI@jf770n72A9OX/gw1aG07fUslLrBw "Rust – Try It Online")
P006:[Try it online!](https://tio.run/##RY7BDoIwEETP9itGTttYmoI3Df4KIQgJSSlKi5IA316LYtjDZrI7mXn9YJ33tYHt9KsijviG5pxiYgijKweyQysQVt7VuX3yCygYxOriyNiBlJSJSrisO30nUgKKC8xFWQqMMygIq …
> some improvements from learning rust

- CONTRIBUTING.md
- README.md
- src/001/p001.fsx
- src/002/p002.fsx
Explain the reasoning behind your solution here.
P001: [Try it online!](https://tio.run/##SyvWTc4vSv3/Pye1RMEls8yp0ji/yFQhT8GWSwEI8hRUFYwVbBUMFGpqwBxTEIeLC6S6OD@nLBWqrji1UKHaUE/P0MDAQNewFixWY6cQnFqol5aZU5JahDAbWa4oNaU0OVVBQ1uTi6ugKDOvJC1PQUk1Uwli9v//AA "F# (.NET Core) – Try It Online")
P002: [Try it online!](https://tio.run/##XU7BDoIwFLvzFQ0JyVsEg8Yr@wkOnkHf4uLYkA1P/vucoAds0qbJa1@qfHVxE8doOEDp3gceQV2JXqDJkNC6ganDDn0JSlysEFmGT8U78@RvElSXOIjVvyRafuxnq5y5/j5vTqG78/mmDYNICpzqBdu60ibwBFKzhUUlkxQ4osFfzs9DGjRO2gZlkRc6X5fF@AY "F# (.NET Core) – Try It Online")
> opening up F#

- src/010/p010.cpp
The isPrime(x) function checks if the int x has any factors between 1 and itself. If it doesn't, the solve() function will add it to the sum.
The algorithm tests every number under two million, so it takes a while.
```
Real time: 60.003 s
User time: 0.352 s
Sys. time: 0.077 s
CPU share: 0.71 %
```
> Adding C++ 010
